// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbxyldBgdRNwOfQ8pOQN3w_tAL6oaUe4VOFpCJ6sSg9Q85CIliUhjbA1otlESguLByRqTw/exec";
